// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMazix2Dniv800YFyzfOVqL97RJXozx-Q',
    appId: '1:984483870222:web:83ad949077784279d6ae5f',
    messagingSenderId: '984483870222',
    projectId: 'personal-task-manager-ap-11983',
    authDomain: 'personal-task-manager-ap-11983.firebaseapp.com',
    storageBucket: 'personal-task-manager-ap-11983.firebasestorage.app',
    measurementId: 'G-RMYWQRNXFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdUWqvWcS-HOqntRZHxNm-GlM2KBzqDU',
    appId: '1:984483870222:android:a3ebc1d7324bfaf6d6ae5f',
    messagingSenderId: '984483870222',
    projectId: 'personal-task-manager-ap-11983',
    storageBucket: 'personal-task-manager-ap-11983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDix1WvRCcPt_eIjO02EuUebJ2GPPs6Uhw',
    appId: '1:984483870222:ios:52c627d31149e37bd6ae5f',
    messagingSenderId: '984483870222',
    projectId: 'personal-task-manager-ap-11983',
    storageBucket: 'personal-task-manager-ap-11983.firebasestorage.app',
    iosBundleId: 'com.example.personaltaskmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDix1WvRCcPt_eIjO02EuUebJ2GPPs6Uhw',
    appId: '1:984483870222:ios:52c627d31149e37bd6ae5f',
    messagingSenderId: '984483870222',
    projectId: 'personal-task-manager-ap-11983',
    storageBucket: 'personal-task-manager-ap-11983.firebasestorage.app',
    iosBundleId: 'com.example.personaltaskmanagerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMazix2Dniv800YFyzfOVqL97RJXozx-Q',
    appId: '1:984483870222:web:9ca9c122e485e0fad6ae5f',
    messagingSenderId: '984483870222',
    projectId: 'personal-task-manager-ap-11983',
    authDomain: 'personal-task-manager-ap-11983.firebaseapp.com',
    storageBucket: 'personal-task-manager-ap-11983.firebasestorage.app',
    measurementId: 'G-4T2PHTGWTK',
  );
}
